name: aogosto_carnes
description: App de entregas Ao Gosto Carnes
version: 1.2.1+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Suas dependências atuais (mantive tudo)
  mobile_scanner: ^7.0.1
  http: ^1.2.2
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^30.2.4
  html: ^0.15.4
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  mime: ^2.0.0
  package_info_plus: ^8.0.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  webview_flutter: ^4.0.0
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.3.1
  location: ^7.0.0
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.15.2

  cloud_firestore: ^5.4.4

  # SHOREBIRD CORRETO (esse é o oficial!)
  shorebird_code_push: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/go-icon.png
    - .env
    - shorebird.yaml